// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_test;

namespace dotnet_test.Migrations
{
    [DbContext(typeof(HealthcareContext))]
    [Migration("20180927214501_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotnet_test.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Obs");

                    b.HasKey("MedicineID");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("dotnet_test.Models.TypeUsers", b =>
                {
                    b.Property<int>("ETypeUsers");

                    b.Property<int?>("UsersID");

                    b.HasKey("ETypeUsers");

                    b.HasIndex("UsersID");

                    b.ToTable("TypeUsers");
                });

            modelBuilder.Entity("dotnet_test.Models.Users", b =>
                {
                    b.Property<int>("UsersID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("crm");

                    b.HasKey("UsersID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dotnet_test.Models.TypeUsers", b =>
                {
                    b.HasOne("dotnet_test.Models.Users")
                        .WithMany("TypeUsers")
                        .HasForeignKey("UsersID");
                });
#pragma warning restore 612, 618
        }
    }
}
